name: Release
on:
  workflow_dispatch:
  # push:
  #   branches: [master, dev]
  # pull_request:
  #   branches: [master, dev]

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: [check]
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - name: Checkout git files
        uses: actions/checkout@v2

      - name: Setup pesde
        uses: ernisto/setup-pesde@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - run: chmod +x ./scripts/release-build.sh
      - name: Build demo game
        timeout-minutes: 1
        run: ./scripts/release-build.sh demo